url: http://maxpuckeridge.github.io/
author: Max Puckeridge

markdown: kramdown

include:
  - .nojekyll

exclude:
  - "bower_components"
  - "node_modules"
  - ".gitignore"
  - "bower.json"
  - "Gemfile"
  - "Gemfile.lock"
  - "Gruntfile.coffee"
  - "LICENSE"
  - "package.json"
  - "Rakefile"
  - "README.md"